environment: production

communication:
  url: <%= node["omf"]["frcp"] %>

# Starting up 12 Node Proxy in this RC
resources:
- type: node
  uid: <%= node1A["omf"]["uid"] %>
- type: node
  uid: <%= node1B["omf"]["uid"] %>
- type: node
  uid: <%= node1C["omf"]["uid"] %>
- type: node
  uid: <%= node1D["omf"]["uid"] %>
- type: node
  uid: <%= node2A["omf"]["uid"] %>
- type: node
  uid: <%= node2B["omf"]["uid"] %>
- type: node
  uid: <%= node2C["omf"]["uid"] %>
- type: node
  uid: <%= node2D["omf"]["uid"] %>
- type: node
  uid: <%= node3A["omf"]["uid"] %>
- type: node
  uid: <%= node3B["omf"]["uid"] %>
- type: node
  uid: <%= node3C["omf"]["uid"] %>
- type: node
  uid: <%= node3D["omf"]["uid"] %>

instrument: true

instrumentation:
  domain: <%= node["omf"]["uid"] %>
  omlCollectUri: <%= node["omf"]["oml_collect_uri"] %>

# Customise resources which can be created by this RC
factories:
  load: [
    'omf_rc/resource_proxy/node',
    'omf_rc/resource_proxy/net',
    'omf_rc/resource_proxy/application'
  ]
  # Set default value of resource property
  defaults:
    node:
      topo_file: '/etc/omf/topology'
      topo_check_timeout: <%= node["omf"]["topo_check_timeout"] %>
