environment: production

communication:
  url: <%= node["omf"]["frcp"] %>

# Starting up 12 Node Proxy in this RC
resources:
<% node["omf"]["uids"].each do |uid| %>
- type: node
  uid: <%= uid %>
<% end %>

instrument: true

instrumentation:
  domain: <%= node["omf"]["uid"] %>
  omlCollectUri: <%= node["omf"]["oml_collect_uri"] %>

# Customise resources which can be created by this RC
factories:
  load: [
    'omf_rc/resource_proxy/node',
    'omf_rc/resource_proxy/net',
    'omf_rc/resource_proxy/application'
  ]
  # Set default value of resource property
  defaults:
    node:
      #topo_file: '/etc/omf/topology'
      #topo_check_timeout: <%= node["omf"]["topo_check_timeout"] %>
